.TH stagenda 1 2023-05-05
.SH NAME
stagenda \- Simple Terminal Agenda
.SH SYNOPSIS
.B stagenda
.RB [ OPTION ]
.SH DESCRIPTION
.B stcalc
a simple command-line agenda program written in C
.SH OPTIONS
.TP
.B list
prints agenda to stdout
.TP
.B \-h, \-\-help
prints help menu
.SH Author
Written by Madison Lynch <madi@mxdi.xyz>